language: julia
os:
    - osx
    - linux
julia:
    - release
    - nightly
notifications:
    email: false
script:
    - julia -e 'Pkg.clone(pwd())'
    - julia -e 'Pkg.build("Nettle")'
    - julia --check-bounds=yes --code-coverage=user -e 'Pkg.test("Nettle")'
after_success:
    - julia -e 'cd(Pkg.dir("Nettle")); Pkg.clone("https://github.com/staticfloat/Coverage.jl.git"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
