language: julia
os:
    - osx
    - linux
julia:
    - release
    - nightly
notifications:
    email: false
after_success:
    - julia -e 'cd(Pkg.dir("Nettle")); Pkg.clone("https://github.com/staticfloat/Coverage.jl.git"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
